package FoodOrderingSystem;

import java.awt.Component;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import Admin.panelVendorReg;
import static Utility.FieldValidator.*;
import Utility.IDGenerator;
import java.io.FileWriter;
import Class.Vendor;

/**
 *
 * @author Teoh Peng Kee
 */
public class Admin_ManageUsers_bk extends javax.swing.JFrame {

    private JTable currentTable = null;
    private JPanel selectedPanel_SpecificUserReg = null;
    private panelVendorReg _panelVendorReg; // = new panelVendorReg(); 
    // 

    /**
     * Creates new form Admin_ManageUsers
     */
    public Admin_ManageUsers_bk() {
	initComponents();

	currentTable = customerTable;

	if (currentTable != null) {
	    currentTable.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
		@Override
		public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
		    if (!evt.getValueIsAdjusting()) { // Ensure the event only fires once when selection is final
			populateFormFromTableSelection();
		    }
		}
	    });
	} else {
	    System.out.println("Warning: currentTable is null. Cannot attach selection listener.");
	}

    }

    private void refreshTable(JTable table, String txtFileName, String role) {
	System.out.println("Refreshing table: " + table + " for role: " + role);

	try {
	    DefaultTableModel model = (DefaultTableModel) table.getModel();
	    model.setRowCount(0); // Reset the table

	    FileReader fr = new FileReader(txtFileName);
	    BufferedReader br = new BufferedReader(fr);
	    String read;

	    while ((read = br.readLine()) != null) {
		String[] data = read.split(";"); // Assuming data is separated by semicolons

		Object[] rowData = null;

		switch (role.toLowerCase()) {
		    case "vendor":
			if (data.length >= 11) { // Ensure enough columns exist
			    rowData = new Object[]{
				data[0], // VendorID
				data[1], // First Name
				data[2], // Last Name
				data[3], // DOB
				data[4], // Company Name
				data[5], // Business Registration No.
				data[6], // License Expiry
				data[7], // Contact No.
				data[8], // Address
				data[9], // Email
				data[10] // Vendor Wallet (Deposit for Refund + Revenue Tracking)
			    };
			}
			break;

		    case "customer":
			if (data.length == 6) {
			    rowData = new Object[]{
				data[0], // CustomerID
				data[1], // First Name
				data[2], // Last Name
				data[3], // DOB
				data[4], // Contact No.
				data[5], // Address
				data[6], // Email
				data[7] // Total Credit Amount
			    };
			}
			break;

		    case "runner":
			if (data.length >= 7) {
			    rowData = new Object[]{
				data[0], // RunnerID
				data[1], // First Name
				data[2], // Last Name
				data[3], // DOB
				data[4], // Employee No.
				data[5], // Identification No.
				data[6], // Contact No.
				data[7], // Address
				data[8] // Email
			    };
			}
			break;

		    default:
			System.out.println("Invalid role: " + role);
			break;
		}

		if (rowData != null) {
		    model.addRow(rowData);
		}
	    }

	    br.close(); // Close file reader
	    //System.out.println("Data Import Complete!");

	} catch (Exception e) {
	    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        cboSearch = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel12 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JSeparator();
        jPanel13 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator13 = new javax.swing.JSeparator();
        btnTry = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panelBasicInfo = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txtContactNum = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtaAddress = new javax.swing.JTextArea();
        jPanel15 = new javax.swing.JPanel();
        btnAddUser = new javax.swing.JButton();
        btnEditUser = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        panelUserSpecific = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel37 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        tabViewUserInfo = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        vendorTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        runnerTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        cboRoleRegister = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filter ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel11.setToolTipText("");

        jLabel29.setText("Search By ");

        cboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        cboSearch.setSelectedIndex(-1);
        cboSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSearchActionPerformed(evt);
            }
        });

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel30.setText("Value");

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Action ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        jButton9.setText("Search");
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Reset");
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(cboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30))
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel13.setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registration"));

        jLabel33.setText("UserID");

        jLabel35.setText("Username");

        jLabel38.setText("Password");

        jLabel44.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel44.setText("Suggestions");

        txtID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtID.setForeground(new java.awt.Color(0, 153, 0));
        txtID.setText("-");
        txtID.setEnabled(false);

        txtPassword.setText("jPasswordField1");

        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnTry.setText("Add User");
        btnTry.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsername)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPassword))
                .addGap(13, 13, 13)
                .addComponent(btnTry, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel44)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTry))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setText("Login Credentials");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText("User Information ");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Basic"));

        jLabel45.setText("First Name");

        jLabel46.setText("Last Name");

        jLabel50.setText("DOB");

        jLabel47.setText("Contact Number");

        jLabel48.setText("Email");

        jLabel49.setText("Address");

        txtaAddress.setColumns(20);
        txtaAddress.setLineWrap(true);
        txtaAddress.setRows(5);
        jScrollPane7.setViewportView(txtaAddress);

        javax.swing.GroupLayout panelBasicInfoLayout = new javax.swing.GroupLayout(panelBasicInfo);
        panelBasicInfo.setLayout(panelBasicInfoLayout);
        panelBasicInfoLayout.setHorizontalGroup(
            panelBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBasicInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBasicInfoLayout.createSequentialGroup()
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(panelBasicInfoLayout.createSequentialGroup()
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBasicInfoLayout.createSequentialGroup()
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBasicInfoLayout.createSequentialGroup()
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(panelBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBasicInfoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBasicInfoLayout.createSequentialGroup()
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelBasicInfoLayout.createSequentialGroup()
                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(12, Short.MAX_VALUE)))
        );
        panelBasicInfoLayout.setVerticalGroup(
            panelBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBasicInfoLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panelBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel50)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(txtContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBasicInfoLayout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7))
                .addContainerGap())
            .addGroup(panelBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBasicInfoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel45)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel46)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(212, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(panelBasicInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(panelBasicInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Action ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        btnAddUser.setText("Add User");
        btnAddUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnEditUser.setText("Edit User");
        btnEditUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUserActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnDeleteUser.setText("Delete User");
        btnDeleteUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Basic"));

        javax.swing.GroupLayout panelUserSpecificLayout = new javax.swing.GroupLayout(panelUserSpecific);
        panelUserSpecific.setLayout(panelUserSpecificLayout);
        panelUserSpecificLayout.setHorizontalGroup(
            panelUserSpecificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );
        panelUserSpecificLayout.setVerticalGroup(
            panelUserSpecificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(panelUserSpecific, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(panelUserSpecific, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Security"));

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane5.setViewportView(jTextArea1);

        jLabel37.setText("Security Question Answer");

        jLabel36.setText("Security Question");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField9)
                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jSeparator15))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(494, 494, 494))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabViewUserInfo.setName(""); // NOI18N

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane3.setViewportView(customerTable);

        tabViewUserInfo.addTab("Customer", jScrollPane3);

        vendorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VendorID", "First Name", "Last Name", "DOB", "Company Name", "Business Reg. No.", "License Expiry Date", "Contact No. ", "Address", "Email", "E-Wallet (RM)"
            }
        ));
        jScrollPane2.setViewportView(vendorTable);

        tabViewUserInfo.addTab("Vendor", jScrollPane2);

        runnerTable.setAutoCreateRowSorter(true);
        runnerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jScrollPane4.setViewportView(runnerTable);

        tabViewUserInfo.addTab("Runner", jScrollPane4);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("User Management");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cboRoleRegister.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Vendor", " " }));
        cboRoleRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRoleRegisterActionPerformed(evt);
            }
        });

        jLabel31.setText("Role * ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboRoleRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(tabViewUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 1015, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 46, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabViewUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(cboRoleRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        jScrollPane1.setViewportView(jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSearchActionPerformed
	// TODO add your handling code here:
	//	JOptionPane.showMessageDialog(null, "Search" + cboSearch.getSelectedIndex());
	//
	//	ArrayList<String> cboItems = new ArrayList<String>();
    }//GEN-LAST:event_cboSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
	// TODO add your handling code here:
	try {
	    String searchText = txtSearch.getText().trim(); // Get search text
	    //DefaultTableModel model = (DefaultTableModel) table.getModel();
	    //model.setRowCount(0); // Clear the table before adding data

	    if (searchText.isEmpty()) {
		// If search text is empty, reset the table to show all data
		//refreshData();
	    }

	    FileReader fr = new FileReader("employee.txt");
	    BufferedReader br = new BufferedReader(fr);
	    String line;

	    // Read through the file line by line
	    while ((line = br.readLine()) != null) {
		String[] data = line.split(";");
		String id = data[0].trim();
		String name = data[1].trim();
		String address = data[2].trim();
		String dob = data[3].trim();
		String username = data[4].trim();
		String password = data[5].trim();
		String role = data[6].trim();

		// Check if any field matches the search text
		if (id.equalsIgnoreCase(searchText)
			|| name.equalsIgnoreCase(searchText)
			|| address.equalsIgnoreCase(searchText)
			|| dob.equalsIgnoreCase(searchText)
			|| username.equalsIgnoreCase(searchText)
			|| password.equalsIgnoreCase(searchText)
			|| role.equalsIgnoreCase(searchText)) {
		    // Add the matching record to the table
		    //model.addRow(new Object[]{id, name, address, dob, username, password, role});
		}
	    }
	    br.close(); // Close the file reader
	} catch (IOException e) {
	    JOptionPane.showMessageDialog(null, "Error reading file: " + e.getMessage());
	}
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void cboRoleRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRoleRegisterActionPerformed
	// TODO add your handling code here:

	// Select Tab and table :- Find the corresponding tab index and switch tabs
	if (cboRoleRegister.getSelectedIndex() != -1) {
	    RoleConfig roleConfigInfo = new RoleConfig(cboRoleRegister.getSelectedItem().toString().toLowerCase());
	    String filePath = roleConfigInfo.getSelectedFileName();
	    currentTable = roleConfigInfo.getSelectedTable();

	    int tabIndex = getTabIndexOfTable(currentTable);
	    if (tabIndex != -1) {
		tabViewUserInfo.setSelectedIndex(tabIndex); // Switch to the tab containing the table
		//currentTable = table;
	    }

	    // Populate the search combo box with column names
	    if (currentTable != null) {
		cboSearch.removeAllItems();
		cboSearch.addItem("All");

		TableModel model = currentTable.getModel();
		int columnCount = model.getColumnCount();

		for (int i = 0; i < columnCount; i++) {
		    cboSearch.addItem(model.getColumnName(i));
		}
	    }

	}

	// ### Add Specific Field UI
	panelUserSpecific.removeAll();
	panelUserSpecific.revalidate(); // Refresh layout
	panelUserSpecific.repaint();

	RoleConfig roleConfigInfo = new RoleConfig(cboRoleRegister.getSelectedItem().toString().toLowerCase());
	String filePath = roleConfigInfo.getSelectedFileName();
	JPanel panelfiller = roleConfigInfo.getSelectedPanel();
	selectedPanel_SpecificUserReg = panelfiller;
	currentTable = roleConfigInfo.getSelectedTable();

	//	String filePath = "";  // Update with actual file location
	//	JTable table = null;
	//	JPanel panelfiller = null;
	//
	//	switch (cboRoleRegister.getSelectedItem().toString().toLowerCase()) {
	//	    case "customer":
	//		break;
	//	    case "vendor":
	//		filePath = "vendor.txt";
	//		_panelVendorReg = new panelVendorReg();
	//		panelfiller = _panelVendorReg;
	//		table = vendorTable;
	//		break;
	//	    case "runner":
	//		//panelfiller = runnerTable;
	//		break;
	//	    default:
	//	}
	if (panelfiller != null) {
	    panelfiller.setSize(jPanel18.getSize()); // Ensure it fits inside
	    panelUserSpecific.add(panelfiller);
	    panelUserSpecific.revalidate(); // Refresh layout
	    panelUserSpecific.repaint();    // Redraw UI
	}

	// ### Add Pre-filled info in UI  -
	//# ID Generation
	String IdCreate = IDGenerator.generateID("vendor", filePath);
	txtID.setText(IdCreate);

	//Refresh Table 
	refreshTable(currentTable, filePath, cboRoleRegister.getSelectedItem().toString().toLowerCase());
    }//GEN-LAST:event_cboRoleRegisterActionPerformed

    private void btnTryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTryActionPerformed
	// TODO add your handling code here:
	txtPassword.setEchoChar((char) 0); // Disable password hiding
    }//GEN-LAST:event_btnTryActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
	// TODO add your handling code here:

	//
	try {
	    //
	    java.util.function.Function<String, String> checkEmpty = (value)
		    -> (value == null || value.trim().isEmpty()) ? "-" : value.trim();
	    String dataToWrite = "";
	    //_panelVendorReg.setAllFields(_panelVendorReg., companyName, licenseExpiryDate);

	    panelVendorReg vendorDetails = null;

	    switch (cboRoleRegister.getSelectedItem().toString().toLowerCase()) {
		case "customer":

		    break;
		case "vendor":
		    vendorDetails = (panelVendorReg) selectedPanel_SpecificUserReg;
		    dataToWrite = checkEmpty(txtID.getText().trim()) + ";"
			    + checkEmpty(txtFirstName.getText().trim()) + ";"
			    + checkEmpty(txtLastName.getText().trim()) + ";"
			    + checkEmpty(txtDOB.getText().trim()) + ";"
			    + checkEmpty(vendorDetails.getCompanyName().trim()) + ";"
			    + checkEmpty(vendorDetails.getBusRegistrationNum().trim()) + ";"
			    + checkEmpty(vendorDetails.getLicenseExpiryDate().trim()) + ";"
			    + checkEmpty(txtContactNum.getText().trim()) + ";"
			    + checkEmpty(txtaAddress.getText().trim()) + ";"
			    + checkEmpty(txtEmail.getText().trim()) + ";"
			    + Integer.toString(200) + "\n";
		    break;
		case "runner":

		    break;
		default:
		    // Handle cases where role doesn't match expected values
		    break;

	    }

	    //Writing data into the file
	    String filename = "vendor.txt";
	    FileWriter fw = new FileWriter(filename, true);
	    fw.write(dataToWrite);
	    //		    txtID.getText() + ";"
	    //		    + txtFirstName.getText() + ";"
	    //		    + txtLastName.getText() + ";"
	    //		    + txtDOB.getText() + ";"
	    //		    + _panelVendorReg.getCompanyName() + ";"
	    //		    + _panelVendorReg.getBusRegistrationNum() + ";"
	    //		    + _panelVendorReg.getLicenseExpiryDate() + ";"
	    //		    + txtContactNum.getText() + ";"
	    //		    + txtaAddress.getText() + ";"
	    //		    + txtEmail.getText() + ";" + "\n"
	    //----------------------
	    //                + tx.getText()+ ";"
	    //                + dobtxt.getText()+ ";"
	    //                + usernametxt.getText()+ ";"
	    //                + new String(passwordtxt.getPassword())+ ";"
	    //                + rolecbx.getSelectedItem().toString() + ";"
	    //                + login.getUsername()+"\n"

	    fw.close();
	    JOptionPane.showMessageDialog(null, "Successfully added the data!");

	    //Select the TabbedPane and JTable
	    RoleConfig roleConfigInfo = new RoleConfig(cboRoleRegister.getSelectedItem().toString().toLowerCase());
	    String filePath = roleConfigInfo.getSelectedFileName();

	    refreshTable(currentTable, filePath, cboRoleRegister.getSelectedItem().toString().toLowerCase());
	    int tabIndex = getTabIndexOfTable(currentTable);
	    if (tabIndex != -1) {
		tabViewUserInfo.setSelectedIndex(tabIndex); // Switch to the tab containing the table
	    }

	    //Clear all the fields 
	    //set next vendor ID 
	    String IdCreate = IDGenerator.generateID(cboRoleRegister.getSelectedItem().toString().toLowerCase(), filePath);
	    txtID.setText(IdCreate);

	} catch (IOException e) {
	    JOptionPane.showMessageDialog(null, e.getMessage());
	}
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
	// TODO add your handling code here:
	String role = cboRoleRegister.getSelectedItem().toString().toLowerCase();
	try {
	    // Ensure a table is selected
	    if (currentTable == null) {
		JOptionPane.showMessageDialog(null, "No table selected for editing!");
		return;
	    }

	    // Get the new data from the form (null handling: if empty, replace with "-")
	    String newId = checkEmpty(txtID.getText());
	    //String name = checkEmpty(txtI) //	    String name = checkEmpty(nametxt.getText());
		    //	    String address = checkEmpty(addresstxt.getText());
		    //	    String dob = checkEmpty(dobtxt.getText());
		    //	    String username = checkEmpty(usernametxt.getText());
		    //	    String password = checkEmpty(new String(passwordtxt.getPassword()));
		    // Validate that a row is selected
	    int selectedRow = currentTable.getSelectedRow();
	    if (selectedRow == -1) {
		JOptionPane.showMessageDialog(null, "No record selected for editing!");
		return;
	    }

	    // Get the original ID from the selected row in the table
	    String originalId = (String) currentTable.getValueAt(selectedRow, 0);

	    // Get the correct file based on the selected role
	    RoleConfig roleConfigInfo = new RoleConfig(role);
	    String filePath = roleConfigInfo.getSelectedFileName();
	    if (filePath.isEmpty()) {
		JOptionPane.showMessageDialog(null, "Invalid role selected!");
		return;
	    }

	    // Read all data from the file into a list
	    BufferedReader br = new BufferedReader(new FileReader(filePath));
	    ArrayList<String> lines = new ArrayList<>();
	    String line;
	    while ((line = br.readLine()) != null) {
		lines.add(line);
	    }
	    br.close();

	    // Validate that the new ID does not already exist (except for the original ID)
	    for (String existingLine : lines) {
		String[] data = existingLine.split(";");
		if (data[0].equals(newId) && !data[0].equals(originalId)) {
		    JOptionPane.showMessageDialog(null, "The new ID already exists. Please choose another.");
		    return;
		}
	    }

	    // Rewrite file with updated record
	    FileWriter fw = new FileWriter(filePath);
	    for (int i = 0; i < lines.size(); i++) {
		String existingLine = lines.get(i);
		String[] data = existingLine.split(";");

		if (data[0].equals(originalId)) { // Match using the original ID
		    // Write the updated record with the new ID and other details
//		    fw.write(
//			    newId + ";"
//			    + name + ";"
//			    + address + ";"
//			    + dob + ";"
//			    + username + ";"
//			    + password + ";"
//			    + position + ";"
//			    + login.getUsername() + "\n"
//		    );
		} else {
		    // Write the existing record as-is
		    fw.write(existingLine + "\n");
		}
	    }
	    fw.close();

	    JOptionPane.showMessageDialog(null, "Record updated successfully!");

	    // Refresh the table data
//	    refreshTable(currentTable, filePath, position.toLowerCase());
	} catch (IOException e) {
	    JOptionPane.showMessageDialog(null, "Error updating record: " + e.getMessage());
	}
    }//GEN-LAST:event_btnEditUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
	// TODO add your handling code here:

    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private int getTabIndexOfTable(JTable table) {
	for (int i = 0; i < tabViewUserInfo.getTabCount(); i++) {
	    Component tabComponent = tabViewUserInfo.getComponentAt(i);

	    if (tabComponent instanceof JScrollPane) {
		JScrollPane scrollPane = (JScrollPane) tabComponent;
		Component viewportComponent = scrollPane.getViewport().getView();

		if (viewportComponent == table) {
		    return i; // Found the tab index containing this table
		}
	    }
	}
	return -1; // Table not found in any tab
    }

    private void populateFormFromTableSelection() {
	String role = cboRoleRegister.getSelectedItem().toString().toLowerCase();
	if (currentTable == null) {
	    JOptionPane.showMessageDialog(null, "No table selected.");
	    return;
	}

	int selectedRow = currentTable.getSelectedRow();
	if (selectedRow != -1) { // Ensure a row is selected 

	    switch (role) {
		case "vendor":
		    Vendor vendor = new Vendor();
		    String id = (String) currentTable.getValueAt(selectedRow, 0);
		    String firstName = (String) currentTable.getValueAt(selectedRow, 1);
		    String lastName = (String) currentTable.getValueAt(selectedRow, 2);
		    String dob = (String) currentTable.getValueAt(selectedRow, 3);
		    String businessName = (String) currentTable.getValueAt(selectedRow, 4);
		    String businessRegNum = (String) currentTable.getValueAt(selectedRow, 5);
		    String licenseExpiryDate = (String) currentTable.getValueAt(selectedRow, 6);
		    String contactNum = (String) currentTable.getValueAt(selectedRow, 7);
		    String address = (String) currentTable.getValueAt(selectedRow, 8);
		    String email = (String) currentTable.getValueAt(selectedRow, 9);
		    
		    //txtID.setText()

		    break;

	    }

	    // Handle Null Values Before Setting to Fields
//	    idtxt.setText(id != null ? id : "-");
//	    nametxt.setText(name != null ? name : "-");
//	    addresstxt.setText(address != null ? address : "-");
//	    dobtxt.setText(dob != null ? dob : "-");
//	    usernametxt.setText(username != null ? username : "-");
//	    passwordtxt.setText(password != null ? password : "-");
//	    rolecbx.setSelectedItem(role != null ? role : "-");
	}
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Admin_ManageUsers_bk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Admin_ManageUsers_bk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Admin_ManageUsers_bk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Admin_ManageUsers_bk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Admin_ManageUsers_bk().setVisible(true);
	    }
	});
    }

    class RoleConfig {

	private String role;
	private JTable selectedTable = null;
	private String selectedFileName = "";
	private JPanel selectedPanel = null;

	// Constructor 
	public RoleConfig(String role) {
	    this.role = role.toLowerCase();
	    determineValues();
	}

	// Method to set values based on role
	private void determineValues() {
	    switch (role) {
		case "customer":
		    // No table, panel, or file needed for customer
		    break;
		case "vendor":
		    selectedFileName = "vendor.txt";
		    selectedPanel = new panelVendorReg();
		    selectedTable = vendorTable; // Ensure this is static or pass instance
		    break;
		case "runner":
		    selectedFileName = "runner.txt";
		    selectedPanel = new JPanel(); // Replace with actual Runner panel
		    selectedTable = runnerTable; // Ensure this is static or pass instance
		    break;
		default:
		    // Handle cases where role doesn't match expected values
		    selectedFileName = "";
		    selectedTable = null;
		    selectedPanel = null;
		    break;
	    }
	}

	// Getters
	public JTable getSelectedTable() {
	    return selectedTable;
	}

	public String getSelectedFileName() {
	    return selectedFileName;
	}

	public JPanel getSelectedPanel() {
	    return selectedPanel;
	}

	public String getRole() {
	    return role;
	}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnEditUser;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTry;
    private javax.swing.JComboBox<String> cboRoleRegister;
    private javax.swing.JComboBox<String> cboSearch;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel panelBasicInfo;
    private javax.swing.JPanel panelUserSpecific;
    private javax.swing.JTable runnerTable;
    private javax.swing.JTabbedPane tabViewUserInfo;
    private javax.swing.JTextField txtContactNum;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextArea txtaAddress;
    private javax.swing.JTable vendorTable;
    // End of variables declaration//GEN-END:variables
}
