package FoodOrderingSystem;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import Class.Customer;
import Utility.IDGenerator;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author Teoh Wei Lun
 */
public class Admin_ManageCredits extends javax.swing.JFrame {

    /**
     * Creates new form Admin_ManageCredits
     */
    private String customerID;
    private String notificationID;
    private String topUpAmount;
    private String newTxID;
    private String currBalance;
    private String newBalance;

    public Admin_ManageCredits() {
	initComponents();
	refreshDataNotification();
	notificationTable.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
	    @Override
	    public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
		if (!evt.getValueIsAdjusting()) { // Ensure the event only fires once when the selection is final
		    populateFormFromTableSelection();
		    refreshDataTx(); 
		}
	    }
	});
    }

    public void populateFormFromTableSelection() {
	int selectedRow = notificationTable.getSelectedRow();
	if (selectedRow != -1) { // Ensure a row is selected
	    notificationID = (String) notificationTable.getValueAt(selectedRow, 0);
	    customerID = (String) notificationTable.getValueAt(selectedRow, 1);
	    topUpAmount = (String) notificationTable.getValueAt(selectedRow, 4);

	}

	// get current balance 
	Customer cus = new Customer(customerID);
	currBalance = Double.toString(cus.getCurrentBalance());

	txtCustomerID.setText(customerID);
	txtTopUpAmount.setText(topUpAmount);
	lblCurrBalance.setText(currBalance);
	try {
	    FileReader fr = new FileReader("Transaction.txt");
	    BufferedReader br = new BufferedReader(fr);
	    String read;
	    if ((read = br.readLine()) != null) {
		newTxID = IDGenerator.generateTxID("Transaction.txt");
		txtTxID.setText(newTxID);
	    } else {
		newTxID = "-";
		txtTxID.setText(newTxID);
	    }
	} catch (Exception e) {
	    JOptionPane.showMessageDialog(null, e.getMessage());
	}

    }

    public void refreshDataTx() {
	try {
	    DefaultTableModel model = (DefaultTableModel) TxTable.getModel();
	    model.setRowCount(0);//reset table
	    FileReader fr = new FileReader("Transaction.txt");
	    BufferedReader br = new BufferedReader(fr);
	    String read;

	    while ((read = br.readLine()) != null) {

		String TxID = read.split(";")[0];
		String customerID = read.split(";")[1];
		String date = read.split(";")[2];
		String time = read.split(";")[3];
		String amount = read.split(";")[4];
		String txType = read.split(";")[5];

		model.addRow(
			new Object[]{
			    TxID,
			    customerID,
			    date,
			    time,
			    amount,
			    txType
			}
		);
	    }

	} catch (Exception e) {
	    JOptionPane.showMessageDialog(null, e.getMessage());
	}
    }

    public void refreshDataNotification() {
	try {
	    DefaultTableModel model = (DefaultTableModel) notificationTable.getModel();
	    model.setRowCount(0);//reset table
	    FileReader fr = new FileReader("Notification.txt");
	    BufferedReader br = new BufferedReader(fr);
	    String read;

	    while ((read = br.readLine()) != null) {

		if (read.split(";")[2].toLowerCase().contains("request")) {
		    String notificationID = read.split(";")[0];
		    String customerID = read.split(";")[1];
		    String topUpStatus = read.split(";")[2];
		    String date = read.split(";")[3];
		    String amount = read.split(";")[4];

		    model.addRow(
			    new Object[]{
				notificationID,
				customerID,
				topUpStatus,
				date,
				amount
			    }
		    );
		}

	    }

	} catch (Exception e) {
	    JOptionPane.showMessageDialog(null, e.getMessage());
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxTable = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlTopUp = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txtTopUpAmount = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        txtTxID = new javax.swing.JTextField();
        lblCurrBalance = new javax.swing.JLabel();
        lblAfterBal = new javax.swing.JLabel();
        btnTopUpCredit = new javax.swing.JButton();
        btnGenerateReceipt = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        notificationTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("User Management");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(486, 486, 486))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Transaction Information");

        TxTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TransactionID", "CustomerID", "Date", "Time", "Amount (RM)", "Transaction Type"
            }
        ));
        jScrollPane3.setViewportView(TxTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Credit Top-Up ");

        pnlTopUp.setBorder(javax.swing.BorderFactory.createTitledBorder("Top-Up Info"));

        jLabel9.setText("Transaction ID");

        jLabel10.setText("Customer ID");

        jLabel13.setText("Current Balance ");

        jLabel14.setText("Balance After Top-Up");

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel15.setText("Top-Up Amount ");

        txtTxID.setEnabled(false);

        lblCurrBalance.setText("-");

        lblAfterBal.setText("-");

        javax.swing.GroupLayout pnlTopUpLayout = new javax.swing.GroupLayout(pnlTopUp);
        pnlTopUp.setLayout(pnlTopUpLayout);
        pnlTopUpLayout.setHorizontalGroup(
            pnlTopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopUpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopUpLayout.createSequentialGroup()
                        .addGroup(pnlTopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(pnlTopUpLayout.createSequentialGroup()
                        .addGroup(pnlTopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4)
                            .addGroup(pnlTopUpLayout.createSequentialGroup()
                                .addGroup(pnlTopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 5, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlTopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopUpLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlTopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTopUpAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTxID, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopUpLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlTopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlTopUpLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(pnlTopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCurrBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(lblAfterBal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        pnlTopUpLayout.setVerticalGroup(
            pnlTopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopUpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtTxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopUpLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopUpLayout.createSequentialGroup()
                        .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(pnlTopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTopUpAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(pnlTopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopUpLayout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14))
                    .addGroup(pnlTopUpLayout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCurrBalance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAfterBal)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(pnlTopUpLayout.createSequentialGroup()
                .addComponent(jSeparator6)
                .addContainerGap())
        );

        btnTopUpCredit.setText("Top-Up Credit");
        btnTopUpCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopUpCreditActionPerformed(evt);
            }
        });

        btnGenerateReceipt.setText("Generate Receipt");
        btnGenerateReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlTopUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTopUpCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGenerateReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTopUpCredit)
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerateReceipt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlTopUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        notificationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NotificationID", "CustomerID", "Status", "Date", "Amount (RM)"
            }
        ));
        jScrollPane4.setViewportView(notificationTable);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Notification");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))
                        .addGap(664, 664, 664))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1169, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTopUpCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopUpCreditActionPerformed
	// TODO add your handling code here:
	double newBalance = 0.0;
	if (validateTopUp(txtTxID, txtCustomerID, txtTopUpAmount)) {
	    newBalance = Double.parseDouble(currBalance) + Double.parseDouble(txtTopUpAmount.getText());
	    updateCustomerCreditAmount(Double.parseDouble(String.format("%.2f", newBalance)));
	    writeToTxFile(customerID, Double.parseDouble(String.format("%.2f", newBalance)), "Credit");
	    refreshDataTx();
	    writeToNotificationFile(notificationID);
	    refreshDataNotification();
	    this.newBalance = String.format("%.2f", newBalance);
	}
    }//GEN-LAST:event_btnTopUpCreditActionPerformed

    private void btnGenerateReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReceiptActionPerformed
	// TODO add your handling code here:
	String content = "";

	// Get current date and time
	LocalDateTime now = LocalDateTime.now();
	DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
	DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("hh:mm:ss a");

	String currentDate = now.format(dateFormatter);
	String currentTime = now.format(timeFormatter);

	content = ("========== Receipt =========\n"
		+ "Date: " + currentDate + "\n"
		+ "Time: " + currentTime + "\n"
		+ "Previous Balance : " + this.currBalance + "\n"
		+ "TopUp Amount : " + "RM" + this.topUpAmount + "\n"
		+ "Current Balance: " + "RM" + this.newBalance + "\n");

    }//GEN-LAST:event_btnGenerateReceiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Admin_ManageCredits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Admin_ManageCredits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Admin_ManageCredits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Admin_ManageCredits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Admin_ManageCredits().setVisible(true);
	    }
	});
    }

    private void setNumericOnly(JTextField textField) {
	((AbstractDocument) textField.getDocument()).setDocumentFilter(new DocumentFilter() {
	    @Override
	    public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
		if (string.matches("\\d+")) {
		    super.insertString(fb, offset, string, attr);
		}
	    }

	    @Override
	    public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
		if (text.matches("\\d+")) {
		    super.replace(fb, offset, length, text, attrs);
		}
	    }
	});
    }

    public void readDataFromCustomer() {
	String read;
	String temporaryCID = "";
	String temporaryAmountHold = "";

	try {
	    FileReader fr = new FileReader("Customer Profile.txt");
	    BufferedReader br = new BufferedReader(fr);

	    do {
		read = br.readLine();
		if (read == null) {
		    break;
		}
		String[] data = read.split(";");

		temporaryCID = data[0];
		temporaryAmountHold = data[4];

		if (temporaryCID.equalsIgnoreCase("")) { // this.customerId)) {
		    //this.amountBefore = Double.parseDouble(temporaryAmountHold);
		    break;
		}

	    } while (read != null);
	    //BalBeforeTxtBox.setText("RM " + String.format("%.2f", this.amountBefore));
	    br.close();
	} catch (IOException e) {
	    JOptionPane.showMessageDialog(this, "There is no profile of you. Please make sure you have an account with us or contact admin", "System", JOptionPane.ERROR_MESSAGE);
	}

    }

    private void updateCustomerCreditAmount(double updatedCreditAmount) {
	File file = new File("Customer Profile.txt");
	List<String[]> allData = new ArrayList<>();

	try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
	    String line;

	    // Read all lines into an ArrayList
	    while ((line = reader.readLine()) != null) {
		String[] data = line.split(";");

		// Update credit amount if customer ID matches
		if (data.length > 7 && data[0].equals(this.customerID)) {
		    data[7] = String.valueOf(updatedCreditAmount);
		}

		allData.add(data); // Store modified or unchanged data
	    }
	} catch (IOException e) {
	    JOptionPane.showMessageDialog(this, "Error reading customer profile: " + e.getMessage());
	    return;
	}

	// Write updated data back to the file
	try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
	    for (String[] data : allData) {
		writer.write(String.join(";", data));
		writer.newLine();
	    }
	} catch (IOException e) {
	    JOptionPane.showMessageDialog(this, "Error writing updated credit amount: " + e.getMessage());
	}
    }

    public void writeToTxFile(String customerID, double transactionAmount, String transactionType) {
	File file = new File("Transaction.txt");
	List<String> allData = new ArrayList<>();

	// Generate new Transaction ID (Assuming it increments)
	String newTransactionID = txtTxID.getText();

	// Get current date and time
	LocalDateTime now = LocalDateTime.now();
	DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
	DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("hh:mm:ss a");

	String currentDate = now.format(dateFormatter);
	String currentTime = now.format(timeFormatter);

	try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
	    String line;

	    // Read all lines into an ArrayList
	    while ((line = reader.readLine()) != null) {
		allData.add(line); // Store existing transaction records
	    }
	} catch (IOException e) {
	    JOptionPane.showMessageDialog(null, "Error reading transaction file: " + e.getMessage());
	    return;
	}

	// Format new transaction record
	String newTransactionRecord = newTransactionID + ";" + customerID + ";" + currentDate + ";"
		+ currentTime + ";" + String.format("%.2f", transactionAmount) + ";" + transactionType;

	// Add new transaction record to list
	allData.add(newTransactionRecord);

	// Write all data back to the file
	try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
	    for (String record : allData) {
		writer.write(record);
		writer.newLine();
	    }
	} catch (IOException e) {
	    JOptionPane.showMessageDialog(null, "Error writing transaction file: " + e.getMessage());
	}
    }

    public void writeToNotificationFile(String notificationID) {
	File file = new File("Notification.txt");
	List<String[]> allData = new ArrayList<>();

	try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
	    String line;

	    // Read all lines into an ArrayList
	    while ((line = reader.readLine()) != null) {
		String[] data = line.split(";");

		// Update credit amount if customer ID matches
		if (data.length > 3 && data[0].equals(notificationID)) {
		    data[2] = String.valueOf("Topup Done");
		}

		allData.add(data); // Store modified or unchanged data
	    }
	} catch (IOException e) {
	    JOptionPane.showMessageDialog(this, "Error reading customer profile: " + e.getMessage());
	    return;
	}

	// Write updated data back to the file
	try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
	    for (String[] data : allData) {
		writer.write(String.join(";", data));
		writer.newLine();
	    }
	} catch (IOException e) {
	    JOptionPane.showMessageDialog(this, "Error writing updated credit amount: " + e.getMessage());
	}
    }

    public static boolean validateTopUp(JTextField txtTxID, JTextField txtCustomerID, JTextField txtTopUpAmount) {
	while (true) {
	    // Check if any field is empty
	    if (txtTxID.getText().trim().isEmpty()) {
		JOptionPane.showMessageDialog(null, "Transaction ID cannot be empty!", "Input Error", JOptionPane.ERROR_MESSAGE);
		txtTxID.requestFocus();
		return false;
	    }
	    if (txtCustomerID.getText().trim().isEmpty()) {
		JOptionPane.showMessageDialog(null, "Customer ID cannot be empty!", "Input Error", JOptionPane.ERROR_MESSAGE);
		txtCustomerID.requestFocus();
		return false;
	    }
	    if (txtTopUpAmount.getText().trim().isEmpty()) {
		JOptionPane.showMessageDialog(null, "Top-Up Amount cannot be empty!", "Input Error", JOptionPane.ERROR_MESSAGE);
		txtTopUpAmount.requestFocus();
		return false;
	    }

	    // Validate Customer ID (must be a String without numbers)
	    if (!txtCustomerID.getText().matches("[A-Za-z0-9]+")) {
		JOptionPane.showMessageDialog(null, "Customer ID must be alphanumeric!", "Input Error", JOptionPane.ERROR_MESSAGE);
		txtCustomerID.requestFocus();
		return false;
	    }

	    // Validate Top-Up Amount (must be a valid number)
	    try {
		double amount = Double.parseDouble(txtTopUpAmount.getText());
		if (amount <= 0) {
		    JOptionPane.showMessageDialog(null, "Top-Up Amount must be greater than 0!", "Input Error", JOptionPane.ERROR_MESSAGE);
		    txtTopUpAmount.requestFocus();
		    return false;
		}
	    } catch (NumberFormatException ex) {
		JOptionPane.showMessageDialog(null, "Top-Up Amount must be a valid number!", "Input Error", JOptionPane.ERROR_MESSAGE);
		txtTopUpAmount.requestFocus();
		return false;
	    }

	    // If all validations pass
	    return true;
	}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TxTable;
    private javax.swing.JButton btnGenerateReceipt;
    private javax.swing.JButton btnTopUpCredit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblAfterBal;
    private javax.swing.JLabel lblCurrBalance;
    private javax.swing.JTable notificationTable;
    private javax.swing.JPanel pnlTopUp;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtTopUpAmount;
    private javax.swing.JTextField txtTxID;
    // End of variables declaration//GEN-END:variables
}
