package FoodOrderingSystem;

import java.awt.Component;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Teoh Peng Kee
 */
public class ManageVendorItemsPage extends javax.swing.JFrame {

    private static String currentVendorID = "";

    /**
     * Creates new form VendorItemsPage
     */
    public ManageVendorItemsPage() {
	initComponents();
	setPanelEnabled(panelVendorFilter, false);
	DefaultListModel<String> vendorListModel = new DefaultListModel<>();
	lstVendor.setModel(vendorListModel);
	lstVendor.addListSelectionListener(new ListSelectionListener() {
	    @Override
	    public void valueChanged(ListSelectionEvent e) {
		if (!e.getValueIsAdjusting()) {
		    String selectedVendor = lstVendor.getSelectedValue();
		    if (selectedVendor != null) {
			setCurrentVendorID(selectedVendor.split(",")[0]);
			refreshData(true);
		    }
		}
	    }
	});

//	vendorMenuListTable.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
//            @Override
//            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
//                if (!evt.getValueIsAdjusting()) { // Ensure the event only fires once when the selection is final
//                    populateFormFromTableSelection();
//                }
//            }
//        });
    }

    private String getCurrentVendorID() {
	return currentVendorID;
    }

    private void setCurrentVendorID(String id) {
	this.currentVendorID = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        vendorMenuListTable = new javax.swing.JTable();
        panelVendorFilter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstVendor = new javax.swing.JList<>();
        btnImportVendors = new javax.swing.JButton();
        btnClearVendors = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        btnImportTableAllItems = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Vendor Menu Items");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(5, 5, 5))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        vendorMenuListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VendorID", "MenuID", "Food Item", "Price", "Description", "Stock Status", "ImageURL"
            }
        ));
        jScrollPane3.setViewportView(vendorMenuListTable);

        panelVendorFilter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vendor List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jScrollPane1.setViewportView(lstVendor);

        btnImportVendors.setText("Import Vendors");
        btnImportVendors.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImportVendors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportVendorsActionPerformed(evt);
            }
        });

        btnClearVendors.setText("Clear Vendors");
        btnClearVendors.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClearVendors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearVendorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVendorFilterLayout = new javax.swing.GroupLayout(panelVendorFilter);
        panelVendorFilter.setLayout(panelVendorFilterLayout);
        panelVendorFilterLayout.setHorizontalGroup(
            panelVendorFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVendorFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVendorFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVendorFilterLayout.createSequentialGroup()
                        .addComponent(btnImportVendors, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVendorFilterLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelVendorFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClearVendors, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelVendorFilterLayout.setVerticalGroup(
            panelVendorFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVendorFilterLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImportVendors)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearVendors)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnImportTableAllItems.setText("Import Menu Items");
        btnImportTableAllItems.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImportTableAllItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportTableAllItemsActionPerformed(evt);
            }
        });

        btnClear.setText("Clear Table");
        btnClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Item");
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImportTableAllItems, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnImportTableAllItems)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelVendorFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelVendorFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnClose.setText("Close");
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setPreferredSize(new java.awt.Dimension(95, 25));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportVendorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportVendorsActionPerformed
	// TODO add your handling code here:
	try {
	    DefaultListModel<String> model = (DefaultListModel<String>) lstVendor.getModel();
	    model.clear();
	    FileReader fr = new FileReader("vendor.txt");
	    BufferedReader br = new BufferedReader(fr);
	    String read;

	    while ((read = br.readLine()) != null) {
		String vendorID = read.split(";")[0];
		String companyVendorName = read.split(";")[4];
		model.addElement(vendorID + "," + companyVendorName);
	    }

	    //
	} catch (Exception e) {
	    System.out.println(e.getMessage());
	    JOptionPane.showMessageDialog(null, e.getMessage());
	}

    }//GEN-LAST:event_btnImportVendorsActionPerformed

    private void btnImportTableAllItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportTableAllItemsActionPerformed
	// TODO add your handling code here:
	refreshData(false);
	setPanelEnabled(panelVendorFilter, true);

    }//GEN-LAST:event_btnImportTableAllItemsActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
	// TODO add your handling code here:
	DefaultTableModel model = (DefaultTableModel) vendorMenuListTable.getModel();
	model.setRowCount(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
	// TODO add your handling code here:
	try {
	    //get selected row of data
	    int selectedRow = vendorMenuListTable.getSelectedRow();
	    String vendorId = (String) vendorMenuListTable.getValueAt(selectedRow, 0);
	    String foodId = (String) vendorMenuListTable.getValueAt(selectedRow, 1);
	    FileReader fr = new FileReader("Menu.txt");
	    BufferedReader br = new BufferedReader(fr);
	    String read;

	    ArrayList<ArrayList<String>> menuList = new ArrayList<>();
	    while ((read = br.readLine()) != null) {
		ArrayList<String> recordMenu = new ArrayList<>();
		recordMenu.add(read.split(";")[0]);
		recordMenu.add(read.split(";")[1]);
		recordMenu.add(read.split(";")[2]);
		recordMenu.add(read.split(";")[3]);
		recordMenu.add(read.split(";")[4]);
		recordMenu.add(read.split(";")[5]);
		recordMenu.add(read.split(";")[6]);
		menuList.add(recordMenu);
	    }
	    for (int row = 0; row < menuList.size(); row++) {
		if (menuList.get(row).get(0).equals(vendorId) && menuList.get(row).get(1).equals(foodId)) {
		    menuList.remove(row);

		    break;
		}
	    }

	    // Writing the updated TODO records back to the file
	    FileWriter fw = new FileWriter("Menu.txt");
	    for (int i = 0; i < menuList.size(); i++) {
		fw.write(menuList.get(i).get(0) + ";");
		fw.write(menuList.get(i).get(1) + ";");
		fw.write(menuList.get(i).get(2) + ";");
		fw.write(menuList.get(i).get(3) + ";");
		fw.write(menuList.get(i).get(4) + ";");
		fw.write(menuList.get(i).get(5) + ";");
		fw.write(menuList.get(i).get(6) + ";\n");
	    }

	    fw.close();
	    this.refreshData(true);
	    JOptionPane.showMessageDialog(null, "Successfully deleted a record!");
	} catch (IOException e) {
	    JOptionPane.showMessageDialog(null, "File error: " + e.getMessage());
	} catch (Exception e) {
	    JOptionPane.showMessageDialog(null, "Unexpected error: " + e.getMessage() + "\n\nPlease Select a record only can proceed for deletion.");
	}

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
	// TODO add your handling code here:
	this.dispose(); 
	new HomePageManager().setVisible(true);
	//new Login().setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnClearVendorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearVendorsActionPerformed
	// TODO add your handling code here:
	DefaultTableModel modelTable = (DefaultTableModel) vendorMenuListTable.getModel();
	modelTable.setRowCount(0);
	DefaultListModel<String> modelList = (DefaultListModel<String>) lstVendor.getModel();
	modelList.clear();
	setPanelEnabled(panelVendorFilter, false);
    }//GEN-LAST:event_btnClearVendorsActionPerformed

    // Author Generated Code 
    public void refreshData(boolean isVendorSelected) {
	try {
	    DefaultTableModel model = (DefaultTableModel) vendorMenuListTable.getModel();
	    model.setRowCount(0);//reset table
	    FileReader fr = new FileReader("Menu.txt");
	    BufferedReader br = new BufferedReader(fr);
	    String read;
	    while ((read = br.readLine()) != null) {
		if (this.currentVendorID.equalsIgnoreCase(read.split(";")[0]) || !isVendorSelected) {
		    String vendorID = read.split(";")[0];
		    String foodID = read.split(";")[1];
		    String foodName = read.split(";")[2];
		    String foodPrice = read.split(";")[3];
		    String foodDescription = read.split(";")[4];
		    String stockStatus = read.split(";")[5];
		    String foodImgLocation = read.split(";")[6];

		    model.addRow(
			    new Object[]{
				vendorID,
				foodID,
				foodName,
				foodPrice,
				foodDescription,
				stockStatus,
				foodImgLocation
			    }
		    );
		}

//                if (read.split(";")[7].equals(login.getUsername())) {
//                    String vendorID = read.split(";")[0];
//                    String foodID = read.split(";")[1];
//                    String address = read.split(";")[2];
//                    String dob = read.split(";")[3];
//                    String username = read.split(";")[4];
//                    String password = read.split(";")[5];
//                    String role = read.split(";")[6];
//                    model.addRow(
//                            new Object[]{id, name, address, dob, username, password,
//                                role});
//                }
	    }

//===================================================================================//
//	    ArrayList<String> lines = File_Manager.fileHandlerRead("Menu.txt"); 
//	    for(int i = 0; i < lines.size(); i++){
//		String[] elements =  lines.get(i).split(";");
//		model.addRow(
//			new Object[]{
//			    elements[0],
//			    elements[1],
//			    elements[2],
//			    elements[3],
//			    elements[4],
//			    elements[5],
//			    elements[6]
//			}	
//		);
//	    }
	    // Message 
	    //JOptionPane.showMessageDialog(null, "Data Import Complete!");
	} catch (Exception e) {
	    JOptionPane.showMessageDialog(null, e.getMessage());
	}
    }

    private void setPanelEnabled(JPanel panel, boolean enabled) {
	for (Component comp : panel.getComponents()) {
	    comp.setEnabled(enabled);
	}
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(ManageVendorItemsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(ManageVendorItemsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(ManageVendorItemsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(ManageVendorItemsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new ManageVendorItemsPage().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearVendors;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnImportTableAllItems;
    private javax.swing.JButton btnImportVendors;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstVendor;
    private javax.swing.JPanel panelVendorFilter;
    private javax.swing.JTable vendorMenuListTable;
    // End of variables declaration//GEN-END:variables
}
