package FoodOrderingSystem;

import Class.*;
import java.awt.Component;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Teoh Peng Kee
 */
public class VendorDashboard extends javax.swing.JFrame {

    private String vendorNameSelected;
    private double revenueSum;
    private int revenueRecordCount;
    /**
     * Creates new form ViewVendorDashboard
     */
    private String vendor_id = "";

    public VendorDashboard() {
	initComponents();
	DefaultListModel<String> vendorListModel = new DefaultListModel<>();
	lstVendor.setModel(vendorListModel);
	setPanelEnabled(pnlFilter, false, false);

	TableModel model = revenueTable.getModel();
	int columnCount = model.getColumnCount();

//	employeeTable.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
//	    @Override
//	    public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
//		if (!evt.getValueIsAdjusting()) { // Ensure the event only fires once when the selection is final
//		    populateFormFromTableSelection();
//		}
//	    }
//	});
	lstVendor.addListSelectionListener(e -> {
	    if (!e.getValueIsAdjusting()) {
		String selectedVendor = lstVendor.getSelectedValue();
		if (selectedVendor != null) {
		    //loadOrders(selectedVendor);
		    String id = lstVendor.getSelectedValue().split(",")[0];
		    vendor_id = id;
		    refreshRevenueData(id, true);
		    lblRevenue.setText(String.format("%.2f", revenueSum));
		    lblOrderCount.setText(String.valueOf(revenueRecordCount));
		    populateYearOptions();
		    populateMonthOptions();
		}
	    }
	});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void setVendorName(String vendorName) {
	this.vendorNameSelected = vendorName;
    }

    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        lblRevenue = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        revenueTable = new javax.swing.JTable();
        jDesktopPane9 = new javax.swing.JDesktopPane();
        jLabel57 = new javax.swing.JLabel();
        lblOrderCount = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstVendor = new javax.swing.JList<>();
        btnImportVendors = new javax.swing.JButton();
        pnlFilter = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        cboMonth = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        cboYear = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        spnDay = new javax.swing.JSpinner();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Vendor Dashboard");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(5, 5, 5))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Orders Information");

        jDesktopPane5.setPreferredSize(new java.awt.Dimension(246, 153));

        jLabel45.setBackground(new java.awt.Color(255, 255, 255));
        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Total Revenue");

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("RM");

        lblRevenue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRevenue.setForeground(new java.awt.Color(255, 255, 255));
        lblRevenue.setText("-");

        jDesktopPane5.setLayer(jLabel45, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(jLabel46, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(lblRevenue, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane5Layout.createSequentialGroup()
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDesktopPane5Layout.createSequentialGroup()
                        .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addGap(170, 170, 170))))
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel45)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(lblRevenue))
                .addGap(45, 45, 45))
        );

        revenueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "RunnerID", "CustomerID", "Year", "Month", "Day", "Food", "Amount (RM)", "Delivery Fee (RM)", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(revenueTable);

        jDesktopPane9.setPreferredSize(new java.awt.Dimension(246, 153));

        jLabel57.setBackground(new java.awt.Color(255, 255, 255));
        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Total Orders");

        lblOrderCount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblOrderCount.setForeground(new java.awt.Color(255, 255, 255));
        lblOrderCount.setText("-");

        jDesktopPane9.setLayer(jLabel57, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane9.setLayer(lblOrderCount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane9Layout = new javax.swing.GroupLayout(jDesktopPane9);
        jDesktopPane9.setLayout(jDesktopPane9Layout);
        jDesktopPane9Layout.setHorizontalGroup(
            jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderCount, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jDesktopPane9Layout.setVerticalGroup(
            jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane9Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel57)
                .addGap(18, 18, 18)
                .addComponent(lblOrderCount)
                .addGap(45, 45, 45))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filter ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel11.setToolTipText("");

        lstVendor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vendor List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        lstVendor.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstVendorValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstVendor);

        btnImportVendors.setText("Import Vendors");
        btnImportVendors.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImportVendors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportVendorsActionPerformed(evt);
            }
        });

        pnlFilter.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSearch.setText("Search");
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel29.setText("Search By ");

        jLabel32.setText("Month");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        cboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        jLabel33.setText("Year");

        cboYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel34.setText("Day");

        javax.swing.GroupLayout pnlFilterLayout = new javax.swing.GroupLayout(pnlFilter);
        pnlFilter.setLayout(pnlFilterLayout);
        pnlFilterLayout.setHorizontalGroup(
            pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFilterLayout.createSequentialGroup()
                        .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlFilterLayout.createSequentialGroup()
                                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                        .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlFilterLayout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnDay, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFilterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlFilterLayout.setVerticalGroup(
            pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFilterLayout.createSequentialGroup()
                        .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(cboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(cboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFilterLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel34))
                            .addGroup(pnlFilterLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(spnDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnSearch)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImportVendors, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(pnlFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnImportVendors)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnClose.setText("Close");
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jDesktopPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(83, 83, 83)
                            .addComponent(jDesktopPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesktopPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addGap(38, 38, 38))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstVendorValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstVendorValueChanged
	// TODO add your handling code here:
	//DefaultListModel<String> model = (DefaultListModel<String>) lstVendor.getModel();
	//JOptionPane.showMessageDialog(null, lstVendor.getSelectedValue());


    }//GEN-LAST:event_lstVendorValueChanged

    private void btnImportVendorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportVendorsActionPerformed
	// TODO add your handling code here:
	try {
	    DefaultListModel<String> model = (DefaultListModel<String>) lstVendor.getModel();
	    model.clear();
	    FileReader fr = new FileReader("vendor.txt");
	    BufferedReader br = new BufferedReader(fr);
	    String read;

	    while ((read = br.readLine()) != null) {
		String vendorID = read.split(";")[0];
		String companyVendorName = read.split(";")[4];
		model.addElement(vendorID + ", " + companyVendorName);
	    }

	    //JOptionPane.showMessageDialog(null, "Vendors list import complete!");
	    setPanelEnabled(pnlFilter, true, true);

	    //
	} catch (Exception e) {
	    System.out.println(e.getMessage());
	    JOptionPane.showMessageDialog(null, e.getMessage());
	}
    }//GEN-LAST:event_btnImportVendorsActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
	// TODO add your handling code here:
	String year = cboYear.getSelectedItem().toString().trim();
	String month = cboMonth.getSelectedItem().toString().trim();
	String day = spnDay.getValue().toString().trim();
	filterOrders(year, month, day);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
	try {
	    String searchText = txtSearch.getText().trim(); // Get search text
	    DefaultTableModel model = (DefaultTableModel) revenueTable.getModel();
	    model.setRowCount(0); // Clear the table before adding data

	    if (searchText.isEmpty()) {
		// If search text is empty, reset the table to show all data
		refreshRevenueData(vendor_id, false);
		lblRevenue.setText(String.format("%.2f", revenueSum));
		lblOrderCount.setText(String.valueOf(revenueRecordCount));
	    }

	    FileReader fr = new FileReader("Order Status.txt");
	    BufferedReader br = new BufferedReader(fr);
	    String line;

	    // Read through the file line by line
	    while ((line = br.readLine()) != null) {
		String[] data = line.split(";");
		String feedbackID = data[0].trim();  // Order ID
		//String vendorID = data[1].trim();    // Vendor ID
		String runnerID = data[2].trim();    // Runner ID (can be null)
		String customerID = data[3].trim();  // Customer ID
		String year = data[4].trim();        // Year
		String month = data[5].trim();       // Month
		String day = data[6].trim();         // Day
		String foodItem = data[7].trim();    // Food Item
		String price = data[8].trim();       // Price
		String deliveryFee = data[9].trim();     // Ratings
		//String quantity = data[10].trim();   // Quantity
		String status = data[11].trim();     // Order Status
		//String comment = data[12].trim();    // Comment

		// Check if any field matches the search text
		if (feedbackID.equalsIgnoreCase(searchText)
			//|| vendorID.equalsIgnoreCase(searchText)
			|| runnerID.equalsIgnoreCase(searchText)
			|| customerID.equalsIgnoreCase(searchText)
			|| year.equalsIgnoreCase(searchText)
			|| month.equalsIgnoreCase(searchText)
			|| day.equalsIgnoreCase(searchText)
			|| foodItem.equalsIgnoreCase(searchText)
			|| price.equalsIgnoreCase(searchText)
			|| deliveryFee.equalsIgnoreCase(searchText)
			//|| quantity.equalsIgnoreCase(searchText)
			|| status.equalsIgnoreCase(searchText)) {
		    //|| comment.equalsIgnoreCase(searchText)) {

		    // Add the matching record to the table
		    model.addRow(new Object[]{
			feedbackID, runnerID, customerID, year, month, day,
			foodItem, price, deliveryFee, status
		    });

		}
	    }
	    br.close(); // Close the file reader
	} catch (IOException e) {
	    JOptionPane.showMessageDialog(null, "Error reading file: " + e.getMessage());
	} catch (Exception e) {
	    JOptionPane.showMessageDialog(null, "Unexpected Error: " + e.getMessage());
	}
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
	this.dispose(); 
	new HomePageManager().setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    //Self written code 
    private void setPanelEnabled(JPanel panel, boolean enabled, boolean exemptSpinner) {
	for (Component comp : panel.getComponents()) {
	    // If exemptSpinner is true, JSpinner components will not be modified
	    if (exemptSpinner && comp instanceof JSpinner) {
		continue;
	    }
	    comp.setEnabled(enabled);
	}
    }

    public void refreshRevenueData(String vendorID, boolean isFilterRequired) {
	try {
	    DefaultTableModel model = (DefaultTableModel) revenueTable.getModel();
	    model.setRowCount(0);//reset table

	    //Vendor ven = new Vendor(); 
//	    
//	    ArrayList<String> vendorInfo = ven.retrieveInfo_ByName(id, name); 
//	    setVendorName(vendorInfo.get(0)); 
	    FileReader fr = new FileReader("Order Status.txt");
	    BufferedReader br = new BufferedReader(fr);
	    String read;
	    Object[] rowData = null;
	    revenueSum = 0;
	    revenueRecordCount = 0;
	    while ((read = br.readLine()) != null) {

		if (read.split(";")[1].trim().equals(vendorID) || !isFilterRequired) {
		    String[] data = read.split(";");

		    String orderID = data[0];
		    String runnerID = data[2];
		    String customerID = data[3];
		    String year = data[4];
		    String month = data[5];
		    String day = data[6];
		    String foodDesc = data[7];
		    String amount = data[8];
		    String deliveryFees = data[9];
		    String status = data[11];

		    rowData = new Object[]{
			orderID, // OrderID
			runnerID, // RunnerID
			customerID, // CustomerID
			year, // Company Name
			month, // Business Registration No.
			day, // License Expiry
			foodDesc, // Contact No.
			amount, // Address
			deliveryFees, // Email
			status // Vendor Wallet (Deposit for Refund + Revenue Tracking)
		    };

		    model.addRow(rowData);
		    revenueSum = revenueSum + Double.parseDouble(amount);
		    revenueRecordCount++;
		}

	    }
	    //JOptionPane.showMessageDialog(null, "Data Import Complete!");
	} catch (Exception e) {
	    JOptionPane.showMessageDialog(null, e.getMessage());
	}
    }

    private void populateYearOptions() {
	Set<String> uniqueYears = new HashSet<>();
	DefaultTableModel model = (DefaultTableModel) revenueTable.getModel();

	for (int i = 0; i < model.getRowCount(); i++) {
	    String year = model.getValueAt(i, 3).toString(); // Assuming Year is in column index 3
	    uniqueYears.add(year);
	}

	cboYear.removeAllItems();
	cboYear.addItem("None"); // Default option

	for (String year : uniqueYears) {
	    cboYear.addItem(year);
	}
    }

    private void populateMonthOptions() {
	Set<String> uniqueMonths = new HashSet<>();
	DefaultTableModel model = (DefaultTableModel) revenueTable.getModel();

	for (int i = 0; i < model.getRowCount(); i++) {
	    String month = model.getValueAt(i, 4).toString(); // Assuming Year is in column index 3
	    uniqueMonths.add(month);
	}

	cboMonth.removeAllItems();
	cboMonth.addItem("None"); // Default option

	for (String month : uniqueMonths) {
	    cboMonth.addItem(month);
	}
    }

    public void filterOrders(String yearInput, String monthInput, String dayInput) {
	List<String[]> filteredOrders = new ArrayList<>();

	try (BufferedReader br = new BufferedReader(new FileReader("Order Status.txt"))) {
	    String line;
	    while ((line = br.readLine()) != null) {
		if (line.split(";")[1].trim().equals(vendor_id)) {
		    String[] parts = line.split(";");
		    if (parts.length > 6) { // Ensure there are enough fields
			String year = parts[4];
			String month = parts[5];
			String day = parts[6];

			boolean matches = (yearInput.equals("None") || year.equals(yearInput))
				|| (monthInput.equals("None") || month.equals(monthInput))
				|| (dayInput.isEmpty() || day.equals(dayInput));

			if (matches) {
			    filteredOrders.add(parts);
			}

		    }
		}

	    }
	} catch (IOException ex) {
	    JOptionPane.showMessageDialog(null, "Error reading file: " + ex.getMessage());
	}

	updateTable(filteredOrders);
    }

    private void updateTable(List<String[]> data) {
	DefaultTableModel model = (DefaultTableModel) revenueTable.getModel();
	model.setRowCount(0); // Clear existing data

	for (String[] row : data) {
	    model.addRow(row);
	}
    }

// Helper method to safely parse integers
    private int parseSafeInt(String value) {
	try {
	    return Integer.parseInt(value.trim());
	} catch (NumberFormatException e) {
	    return 0; // Default if parsing fails
	}
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(VendorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(VendorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(VendorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(VendorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new VendorDashboard().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnImportVendors;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cboMonth;
    private javax.swing.JComboBox<String> cboYear;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JDesktopPane jDesktopPane9;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblOrderCount;
    private javax.swing.JLabel lblRevenue;
    private javax.swing.JList<String> lstVendor;
    private javax.swing.JPanel pnlFilter;
    private javax.swing.JTable revenueTable;
    private javax.swing.JSpinner spnDay;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}
